#统一的配置放到该文件下、测试和生产不同的配置放到test和prod的配置文件下
spring:
  profiles:
    active: test       #默认测试环境、上线的时候修改为prod读取上线环境的配置
  banner:
    location: classpath:static/banner/banner.txt      #自定义banner
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
server:
  servlet:
    session:
      timeout: 600  #session超时时间，默认10分钟