server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://139.224.230.6:3306/nmgwr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: nmgwr
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    exceptionSorter: true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  redis:
    host: 192.168.56.101
    port: 6379
    password: 123456
  devtools:
    restart:
      enabled: true
  session-type: jdbc #重写了spring session type配置，默认不配是单机内存，支持 redis
beetl-beetlsql:
  dev: true #开发模式，修改sql不需要重启