server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nmgwr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: nmgwr
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver