server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://122.112.229.135:8635/nmgwr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: nmgwr
    password: Nmgwr123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
beetl-beetlsql:
  dev: true #开发模式，修改sql不需要重启