server:
  port: 8003
spring:
  datasource:
    url: jdbc:mysql://122.112.229.135:8635/nmgwr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
    username: nmgwr
    password: Nmgwr123!@#
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.56.101
    port: 6379
    password: 123456
  session-type: redis #重写了spring session type配置，默认不配是单机内存，支持redis
beetl-beetlsql:
  dev: false #开发模式，修改sql不需要重启